
'use client';

import { useEffect, useState } from 'react';
import { API_BASE } from '../lib/resident';
import ImagePreview from '../components/ImagePreview';

type Complaint = { id:number; residentName:string; plotNo:string; subject:string; status:string; updates:any[]; createdAt?:string };
function readFiles(files: FileList | null) { return Promise.all(Array.from(files || []).map((file) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || '')); reader.onerror = reject; reader.readAsDataURL(file); }))); }

export default function ComplaintsPage() {
  const [items, setItems] = useState<Complaint[]>([]);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [drafts, setDrafts] = useState<Record<number, { message: string; imageUrls: string[] }>>({});

  async function load(){ const res=await fetch(`${API_BASE}/api/complaints`,{cache:'no-store'}); const json=await res.json(); if(!res.ok) throw new Error(json?.message||'Failed'); setItems(json);} 
  useEffect(()=>{load().catch((e)=>setError(e.message));},[]);
  async function updateStatus(item: Complaint, status: string){ const res=await fetch(`${API_BASE}/api/complaints/${item.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})}); const json=await res.json(); if(!res.ok) throw new Error(json?.message||'Failed'); setMessage(json.message||'Updated'); load(); }
  async function sendMessage(item: Complaint){ const draft = drafts[item.id] || { message:'', imageUrls:[] }; const res=await fetch(`${API_BASE}/api/complaints/${item.id}/message`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sender:'admin', message:draft.message, imageUrls:draft.imageUrls})}); const json=await res.json(); if(!res.ok) throw new Error(json?.message||'Failed'); setDrafts((prev)=>({...prev,[item.id]:{message:'',imageUrls:[]}})); setMessage(json.message||'Message sent'); load(); }
  return <div className="wrap wideWrap"><div className="pageGrid"><section className="card wideCard"><div className="pageHead"><div><h1 className="h1">Complaints</h1><p className="p">Chat-style complaint history. Keep replying while a complaint is open or in progress.</p></div></div>{error?<div className="alert error">{error}</div>:null}{message?<div className="alert success">{message}</div>:null}<div className="chatList">{items.map((item)=><div key={item.id} className="chatCard"><div className="chatHeader"><div><h3 className="h2" style={{marginBottom:6}}>{item.subject}</h3><div className="smallMuted">{item.residentName} • Plot {item.plotNo}</div></div><div className="row"><span className={`badge status ${String(item.status).toLowerCase()==='resolved'?'paid':String(item.status).toLowerCase()==='in_progress'?'partially_paid':'unpaid'}`}>{item.status}</span><button className="btn small" onClick={()=>updateStatus(item,'IN_PROGRESS').catch((e)=>setError(e.message))}>In Progress</button><button className="btn small" onClick={()=>updateStatus(item,'RESOLVED').catch((e)=>setError(e.message))}>Resolve</button></div></div><div className="chatThread">{(item.updates||[]).map((u:any, idx:number)=><div key={idx} className={`bubble ${u.sender || 'system'}`}><div>{u.message}</div>{(u.imageUrls||[]).length?<div className="thumbRow">{u.imageUrls.map((src:string, i:number)=><ImagePreview key={i} src={src} className="thumbImg" />)}</div>:null}<small className="bubbleTime">{u.createdAt ? new Date(u.createdAt).toLocaleString() : ''}</small></div>)}</div>{String(item.status).toUpperCase()!=='RESOLVED'?<div className="chatCompose"><textarea className="inp ta" placeholder="Write update for resident..." value={drafts[item.id]?.message || ''} onChange={(e)=>setDrafts((prev)=>({...prev,[item.id]:{message:e.target.value,imageUrls:prev[item.id]?.imageUrls||[]}}))} /><input className="inp" type="file" accept="image/*" multiple onChange={async (e)=>{ const images = await readFiles(e.target.files); setDrafts((prev)=>({...prev,[item.id]:{message:prev[item.id]?.message || '',imageUrls:[...(prev[item.id]?.imageUrls||[]),...images]}})); e.currentTarget.value=''; }} />{!!(drafts[item.id]?.imageUrls||[]).length?<div className="thumbRow">{(drafts[item.id]?.imageUrls||[]).map((src, idx)=><ImagePreview key={idx} src={src} className="thumbImg" />)}</div>:null}<div className="row"><button className="btn primary" onClick={()=>sendMessage(item).catch((e)=>setError(e.message))}>Send Reply</button></div></div>:null}</div>)}{!items.length?<div className="mutedCell">No complaints found.</div>:null}</div></section></div></div>;
}
